#!/bin/bash
#SBATCH -J Urok
#SBATCH --output=PELE.out
#SBATCH --error=PELE.err
#SBATCH --ntasks=16
#SBATCH --time=00-02:00:00

module purge
module load intel mkl impi gcc
module load impi
module load boost/1.64.0
module load ANACONDA/2019.10

eval "$(conda shell.bash hook)"

conda activate /gpfs/projects/bsc72/conda_envs/platform/1.6.3

python -m pele_platform.main input.yaml
